steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - "--tag=gcr.io/$PROJECT_ID/quickstart-image"
      - "--file=./apps/api/Dockerfile"
images:
  - 'gcr.io/$PROJECT_ID/api'
